### PR TITLE
ci: add golang lint and fixed. #157

### LINKED ISSUE #157: Improve linting
### Feature Description

Currently, k6-operator uses only `yaml-lint` for manifests. Add Golang linters.

### Suggested Solution (optional)

k6 repo can be used as a main reference.

### Already existing or connected issues / PRs (optional)

_No response_

### PR DESCRIPTION
**Pull request by u5surf**
Fixes #157 
Add golangci-lint on github actions ci and fixed some conventional issues of linting.

### CODE REVIEW

File: controllers/testrun_controller.go [hunk 1]
```diff
@@ -268,7 +268,7 @@ func (r *TestRunReconciler) reconcile(ctx context.Context, req ctrl.Request, log
 		// delete if configured
 		if k6.GetSpec().Cleanup == "post" {
 			log.Info("Cleaning up all resources")
-			r.Delete(ctx, k6)
+			r.Delete(ctx, k6) //nolint:errcheck
```
Comment (yorugac) [inline controllers/testrun_controller.go:271]: Can this linter be fixed with smth like:
```
_ = r.Delete(ctx, k6)
```
instead of exception?

File: .github/workflows/golangci-lint.yaml [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version: '1.19'
+          cache: false
+      - name: lint
+        uses: golangci/golangci-lint-action@v3
+        with:
+          version: v1.54
```
Comment (yorugac) [inline .github/workflows/golangci-lint.yaml:19]: The latest is `v1.55.0` according to [official page](https://github.com/golangci/golangci-lint/releases). They update pretty often. Can we try to go with `v1.55`?

File: pkg/types/k6cli.go [hunk 3]
```diff
@@ -14,12 +14,10 @@ type CLI struct {
 
 func ParseCLI(arguments string) *CLI {
 	lastArgV := func(start int, args []string) (end int) {
-		var nextArg bool
 		end = start
-		for !nextArg && end < len(args) {
+		for end < len(args) {
```
Comment (yorugac) [inline pkg/types/k6cli.go:18]: I don't remember why it was written with `nextArg` :sweat_smile: But the change seems to be correct and the unit test is OK... For my understanding, what was the linter that made you add this change?

File: .github/workflows/golangci-lint.yaml [hunk 4]
```diff
@@ -0,0 +1,20 @@
+---
+name: "golangci-lint"
```
Comment (yorugac) [inline .github/workflows/golangci-lint.yaml:2]: Please change:
```suggestion
name: "Golang Lint"
```
I've been trying to keep unified naming in CIs lately.

**Review by yorugac — CHANGES_REQUESTED** [review]
Thanks for working on this, @u5surf! For starters, it's probably fine to go with the default linting as here: we can always add additional rules later :+1: 
I have a few questions and small CRs - please check the comments.

**Comment by yorugac** [comment]
One more thing: can you please add a small instruction / command on how to run this linter locally? It could be a target in Makefile or part of internal docs (i.e. `docs/` folder). It can be very frustrating to fix linting in Github Actions so running it quickly locally is preferable.

File: controllers/testrun_controller.go (hunk 1 above)
Comment (u5surf) [reply controllers/testrun_controller.go:271]: @yorugac 
We also should be fixed like that below?
```
diff --git a/main.go b/main.go
index 169614b..ed60b2f 100644
--- a/main.go
+++ b/main.go
@@ -89,8 +89,8 @@ func main() {
                os.Exit(1)
        }

-       mgr.AddHealthzCheck("health", healthz.Ping)
-       mgr.AddReadyzCheck("ready", healthz.Ping)
+       mgr.AddHealthzCheck("health", healthz.Ping) //nolint:errcheck
+       mgr.AddReadyzCheck("ready", healthz.Ping)   //nolint:errcheck

        if err = (controllers.NewK6Reconciler(&controllers.TestRunReconciler{
                Client: mgr.GetClient(),
```

File: pkg/types/k6cli.go (hunk 3 above)
Comment (u5surf) [reply pkg/types/k6cli.go:18]:
```
pkg/types/k6cli.go:22:5: ineffectual assignment to nextArg (ineffassign)
				nextArg = true
				^
```

Comment (yorugac) [reply pkg/types/k6cli.go:18]: Got it, thanks!

File: controllers/testrun_controller.go (hunk 1 above)
Comment (yorugac) [reply controllers/testrun_controller.go]: If the linter allows it, yes please!

File: Makefile [hunk 5]
```diff
@@ -98,6 +98,10 @@ fmt:
 vet:
 	go vet ./...
 
+# Run golangci-lint
+lint:
+	go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.0
+	golangci-lint --timeout 30m run ./...
```
Comment (yorugac) [inline Makefile:104]: Nice :raised_hands:  Timeout is pretty large: our code base is rather small so shouldn't need that much in theory :thinking:  Either way, this would work, thanks for adding Makefile!

Comment (u5surf) [reply Makefile]: @yorugac 
I could reduce the timeout.

File: controllers/testrun_controller.go (hunk 1 above)
Comment (u5surf) [reply controllers/testrun_controller.go]: @yorugac 
I also fixed these.

File: Makefile (hunk 5 above)
Comment (yorugac) [reply Makefile]: :+1: thanks. It should be fine with 5m, and if not, we can always tinker with it.

**Review by yorugac — APPROVED** [review]
LGTM! Thank you @u5surf, for working on this :smile:
